CREATE TABLE person
(
    id         integer primary key generated by default as identity,
    username      varchar(50) unique,
    first_name varchar(50),
    last_name  varchar(50),
    password   text
);

CREATE TABLE role
(
    id   integer PRIMARY KEY generated always as identity,
    name varchar(20)
);

CREATE TABLE person_role
(
    person_id   int references person (id) on delete cascade,
    role_id int references role (id),
    PRIMARY KEY (person_id, role_id)
);

CREATE TABLE grade
(
    person_id     integer primary key references person (id) on delete cascade,
    grade         integer,
    count         integer,
    average_grade integer
);

CREATE TABLE advert
(
    id          integer primary key generated by default as identity,
    title       varchar(100),
    description text,
    price       integer,
    person_id   integer references person (id) on delete cascade,
    is_actual   boolean,
    is_sale     boolean,
    is_paid     boolean
);



CREATE TABLE comments
(
    id        integer primary key generated by default as identity,
    comment   text,
    advert_id integer references advert (id) on DELETE cascade,
    person_id integer references person (id) on delete cascade,
    create_at timestamp with time zone
);


CREATE TABLE messages
(
    id                  integer primary key generated by default as identity,
    message             text,
    create_person_id    integer references person (id) on delete cascade,
    create_at           timestamp with time zone,
    recipient_person_id integer,
    is_read             boolean
);


CREATE TABLE category(
                         id integer primary key generated by default as identity,
                         name varchar(100)
);

CREATE TABLE advert_category
(
    advert_id   int references advert (id) on delete cascade,
    category_id int references category (id) on delete set null,
    PRIMARY KEY (advert_id, category_id)
);

INSERT INTO role(name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');

